version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pdf-rag-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pdf-rag

  # fastapi:
  #   build: .
  #   container_name: pc-api
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/product_compare
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/code

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: pc-frontend
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - ./frontend:/app  # You can remove this in production
  #   depends_on:
  #     - fastapi